version: 0.0
os: linux
files:
  - source: /
    destination: /api
hooks:
  AfterInstall:
    - location: /api/npm-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: /api/npm-start.sh
      runas: ec2-user
      timeout: 60