version: 0.0
os: linux
files:
  - source: /
    destination: /api
hooks:
  AfterInstall:
    - location: /api/scripts/npm-install.sh
      runas: ubuntu
      timeout: 300
  ApplicationStart:
    - location: /api/scripts/npm-start.sh
      runas: ubuntu
      timeout: 60