version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  AfterInstall:
    - location: npm-install.sh
      timeout: 300
  ApplicationStart:
    - location: npm-start.sh
      timeout: 60

